site_name: KIT Lernfeld 7 (Datenbanken)

theme:
  name: material
  language: de
  font: false
  favicon: bilder/favicon.png
  logo: bilder/logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - include-markdown
  - search

extra_css:
  - 'extra.css'

use_directory_urls: false

repo_url: https://github.com/herr-nm/MMBbS_KIT_LF07DB/

site_url: https://herr-nm.github.io/MMBbS_KIT_LF07DB/

nav:
    - Informationen zur Kurslizenz: 'index.md'
    - Kapitel 00 - Organisatorisches: '00_organisatorisches.md'
    - Kapitel 01 - Vorstellung des Modellunternehmens: '01_modellunternehmen.md'
    - Kapitel 02 - Grundlagen der Datenbanken: '02_grundlagen.md'
    - Kapitel 03 - Datenbanken modellieren: '03_modellieren.md'
    - Kapitel 04 - Datenbanken anlegen: '04_anlegen.md'
    - Kapitel 05 - Datenbanken abfragen: '05_abfragen.md'
    - Kapitel 06 - Datenbanken und ihre Inhalte ändern: '06_aendern.md'